name: rnaseq
channels:
  - bioconda
  - conda-forge
dependencies:
  - hisat2
  - subread
  - samtools
  - r-base=4.3
  - r-dplyr
  - r-ggplot2
  - r-patchwork
  - bioconductor-deseq2
  - bioconductor-annotationdbi
  - bioconductor-org.mm.eg.db
  - r-pheatmap
